Translate recommendation identifiers
metanorma/pubid-itu pull request #48
Opened 2024-09-28 10:16 UTC by mico

related #43 
translate only recommendation identifiers, doesn't affect annexes.

2024-09-29 13:37 UTC, opoudjis approved these changes

2024-09-29 13:45 UTC, opoudjis requested changes
"Annex to" also needs to be translated, as does "OB".

e.g. for French, currently generating `Annex to UIT-R OB No. 1000`. We need `Annexe au BE de l'UIT-R 1000`.

2024-10-08 01:50 UTC, mico commented
> "Annex to" also needs to be translated, as does "OB".
> 
> e.g. for French, currently generating `Annex to UIT-R OB No. 1000`. We need `Annexe au BE de l'UIT-R 1000`.

This pull request only for recommendation translation. I'll do for annexes in the next pull request.

2024-10-08 08:50 UTC, opoudjis commented
OK then, you can merge this.

2024-10-09 05:02 UTC, merged